### ISSUE TITLE
Embed.html desperate needs an upgrade

### ISSUE THREAD

**Issue by Brend-Smits** [DigitalExcellence/dex-frontend#223]
Embedding is a functionality that can be used for Fontys to easily embed projects on the Fontys.nl during an open day or something. 
Currently embeds look like this: https://gyazo.com/6e06161f2c8d39ac04fd09f776ca8978

I asked @MaxKorlaar to temporarily freestyle and fix this design to make it better.

**Comment by MaxKorlaar** [comment]
![image](https://user-images.githubusercontent.com/8917249/84943420-9b22c280-b0e4-11ea-9cc8-2895c51de275.png)

I've hidden the navigation, footer and beta notice when on an embed page.

In case of an even smaller screen width, the sidebar is placed below the main content.

![image](https://user-images.githubusercontent.com/8917249/84943503-bdb4db80-b0e4-11ea-9bef-9ba29a6e72da.png)

This is currently done by listening to router events, but it is not how it really should be done. Because the `<router-outlet>` component is part of the layout itself, I can't easily change what layout should be used through the routes definitions.

I think it would be better if done like this: https://stackblitz.com/edit/angular-multi-layout-example?file=app%2Fapp.routing.ts, in which the routes determine which layout gets loaded, with the other components being child components of this layout, making it easier to add new layouts.

**Comment by Brend-Smits** [comment]
That already looks way better. The tags can also be hidden btw

**Comment by MaxKorlaar** [comment]
I have commented them out, so that they can be brought back in the future.

**Comment by Brend-Smits** [comment]
What does @rubenb994 think of your suggestion for a multi-layout routing setup?

**Comment by rubenb994** [comment]
Seems like a good solution, hiding all layout elements for certain routes does not feel like something we should implement
