### ISSUE TITLE
Header breaks responsiveness on all pages

### ISSUE THREAD

**Issue by MikeKotte** [DigitalExcellence/dex-frontend#258]
**Describe the bug**
Header breaks responsiveness on all pages when viewed on mobile device sizes.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to any page.
2. Scale browser down to mimic small sized windows.

**Expected behaviour**
Pages should be responsive to the screen size.

**Screenshots**
https://imgur.com/r3PMuvD

**Comment by Brend-Smits** [comment]
Heey Mike,
Thanks for submitting an issue. 

Making DeX fully responsive is one of our goals for the upcoming semester, we will be sure to keep you posted on this issue on the progress.

**Comment by Ruby77** [comment]
Okay, after some research on different responsive header/navbar designs, I was wondering: do we expect more links in the header in the future? This is good to know for creating the header right now, otherwise we have to change it again whenever there will be added more links. 
The toggle header would be an idea if we expect more links appearing in the future. If there won't appear more links, we have more flexibility for choosing a design.

I found this page (https://bradfrost.com/blog/post/responsive-nav-patterns/) about different nav patterns with pros and cons. What do you guys think? Thnx 😄

**Comment by Brend-Smits** [comment]
I don't expect new nav-bar tab items getting added anytime soon. We will be adding additional tabs in the dropdown from the account though, things like "Profile, Portfolio, Settings... etc"
I think a toggle might be best for now, we don't have designs for this yet but it's a good start I suppose. When the design updates, we can update our implementation.
