### ISSUE TITLE
Make DeX interactive

### ISSUE THREAD

**Issue by Brend-Smits** [DigitalExcellence/dex-frontend#270]
The website is very clean but could be more interactive. 
Project Overview page is very static, can be catered more towards our target audience

**Comment by Brend-Smits** [comment]
Examples: tag clouds, interesting visuals,

**Comment by Brend-Smits** [comment]
Quick wins:
- Clickable names on the project detail page
- Clickable names on the project overview page, will trigger a search that is specific for the user that you clicked on. (example: https://dex.software/project/overview?query=Max, might be nice to add collaborators to this search as well)
- Ability to follow Projects
- Ability to follow Tags/Categories
- Ability to follow Users
- Setup email notifications: Users might want to get daily/weekly/monthly emails  about interesting projects/followed content. Example is how Github does it based on your personal preferences: https://gyazo.com/d35ef4318f1cd2e7d4ccb52572ec0c7c
- Ability to like Projects
- Add new interactive visuals on the home page: https://dex.software/home and https://dex.software/account/login

**Comment by Brend-Smits** [comment]
I can't help it, to make DeX more interesting to visit and look at. Adding the DeX-ReX to make things more original and to really set up a brand around DeX. We can work on implementing the ReX properly in our designs.

**Comment by StijnGroenen** [comment]
> Quick wins:
> 
> * Clickable names on the project detail page
> * Clickable names on the project overview page, will trigger a search that is specific for the user that you clicked on. (example: https://dex.software/project/overview?query=Max, might be nice to add collaborators to this search as well)
> * Ability to follow Projects
> * Ability to follow Tags/Categories
> * Ability to follow Users
> * Setup email notifications: Users might want to get daily/weekly/monthly emails  about interesting projects/followed content. Example is how Github does it based on your personal preferences: https://gyazo.com/d35ef4318f1cd2e7d4ccb52572ec0c7c
> * Ability to like Projects
> * Add new interactive visuals on the home page: https://dex.software/home and https://dex.software/account/login

I understand that liking projects would help other users find the best projects by using the likes in the discovery algorithm.
I am wondering what the point of following a project is though. Once a project is added to Digital Excellence, it won't change much. The actual activity of the project happens on the original platform (ex. GitHub, GitLab, etc.). If a user is interested in one of the projects, it is more useful for the user to follow the project (and collaborate) on the platform where the project itself is hosted since that is where the updates happen. Digital Excellence is just the discovery tool.
Maybe this is worth discussing?

> I can't help it, to make DeX more interesting to visit and look at. Adding the DeX-ReX to make things more original and to really set up a brand around DeX. We can work on implementing the ReX properly in our designs.

**YES.**

**Comment by Brend-Smits** [comment]
Ah yes... I forgot to update this issue. I talked with Wilrik about this and we came to the same conclusion.
