### ISSUE TITLE
Implement new filter based on new design

### ISSUE THREAD

**Issue by niraymak** [DigitalExcellence/dex-frontend#287]
**Is your feature request related to a problem? Please describe.**
The current filter is using accordion and was based on a temporary design. The 'collapse' icons are also difficult to animate.

**Describe the solution you'd like**
on the next page:
https://dex.software/project/overview on the left panel
the filter menu should be re-implemented using the design found in #413

**Comment by Brend-Smits** [comment]
What's a shrink icon? Could you please give an example? Maybe link to a website that has this functionality.

**Comment by niraymak** [comment]
Wasn't sure about the right term for it. What I mean is shown in the link below.

https://dribbble.com/shots/7334894-Adam-collapse-and-expand-micro-interaction

**Comment by juliaslaats** [comment]
For anyone who will be working on this: I looked at this shortly to give it an animation in #321 but it's a little difficult. Right now the icon is implemented as a background to the title of a category, so it's not easy to manipulate. I didn't look in to it further, since this issue is still open, but wanted to give a heads-up to the person who'll be looking into it 😄

**Comment by Brend-Smits** [comment]
This issue is now regarding the implementation of a new design that is created in #413.
