### ISSUE TITLE
Improve PageSpeed/Lighthouse score

### ISSUE THREAD

**Issue by Niekvandam** [DigitalExcellence/dex-frontend#332]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Additional context**

**Comment by Brend-Smits** [comment]
To further improve lighthouse scores, I've added a Content Delivery Network called Cloudflare.  Cloudflare is a trusted industry leader in CDN's. They offer a great product free of charge. 
Some of the features we're using from them are:
- Analytics (basic)
- Caching
- Compression
- DDoS Mitigation

Our DNS is now also managed at Cloudflare instead of Name.com 
This change has resulted in the following improvement in the score:
![image (3)](https://user-images.githubusercontent.com/15904543/99681181-23cfd100-2a7e-11eb-93cd-772ac7c02c09.png)
The other 'red' and 'orange' scores can definitely be improved by manually tuning some things. I do think the budget.json will need some small changes though.

**Comment by Niekvandam** [comment]
The current CI lighthouse integration does not match the expected results. When a PR is accepted, a push is made to the develop branch, which triggers the CI lighthouse. 

The current lighthouse checks do not add up to the expected score, this could be due to a broad variety of reasons. It mostly seems like the lighthouse executed by github actions does not utilize 100% of it's processing/networking power. Some research can be done regarding the lighthouse actions file, specifically around CPU/network throttling.
