### ISSUE TITLE
Grid layout with cards dex projects page

### ISSUE THREAD

**Issue by liekevdvoort** [DigitalExcellence/dex-frontend#346]
**Is your feature request related to a problem? Please describe.**
To make dex more fun and give options to the user we decided that cards would work well and with the possible future addition of images this makes sense. We want to add the grid layout with cards as the default option but incorporate a switch to go to the list view which has more items on one page and less content in them for a different experience.

**Describe the solution you'd like**
Design a grid card system for the projects page of dex and a switch to toggle to the old layout.

**Additional context**

**Comment by liekevdvoort** [comment]
![image](https://user-images.githubusercontent.com/49523639/98398228-e83a0d80-2060-11eb-8d3c-5fce850f5fbe.png)
This would be made with css grid and a repeat minmax to the columns for automatic responsiveness

**Comment by liekevdvoort** [comment]
![image](https://user-images.githubusercontent.com/49523639/98398336-191a4280-2061-11eb-82f0-a4809f2a6326.png)
Preview of other options and options with images

**Comment by liekevdvoort** [comment]
![image](https://user-images.githubusercontent.com/49523639/98398425-45ce5a00-2061-11eb-8bf5-2e32930f2159.png)

This would be made with css grid and a repeat minmax to the columns for automatic responsiveness

**Comment by liekevdvoort** [comment]
![image](https://user-images.githubusercontent.com/49523639/98398607-84641480-2061-11eb-82cd-0add1a60f05d.png)

**Comment by Brend-Smits** [comment]
I like the last one the most, what does @DigitalExcellence/frontend think? 
Great work Lieke!

**Comment by liekevdvoort** [comment]
![image](https://user-images.githubusercontent.com/49523639/98676303-b9bb7b80-235b-11eb-8b75-073b8b99309e.png)
option with likes

**Comment by juliaslaats** [comment]
How does the option with likes work? When does the icon appear over the card? Because it seems to be in a little bit of a weird position. There is also a separate issue about the possibility to like projects: #281, I'm planning to work on that so maybe I could use a similar approach :)

Besides that I really like how you made the design! Would the (optional) list-view still be the same as it is now? Because it might be nice to give that a small update, to make it look more similar to your cards (and also find a way to display a similar amount of information)

Great work! 👍

**Comment by liekevdvoort** [comment]
It has two options one on a hover with multiple designs (the first image) 
second one has the number of likes in the card and had no hover.

Yes the list view would be the same as it is now, but about the update indeed that's a good suggestion forgot about that i'll look into it. but one of the strengts of the two options system is i think that the cards have more information but less cards on a page and for the list view the other way around

**Comment by juliaslaats** [comment]
> It has two options one on a hover with multiple designs (the first image)
> second one has the number of likes in the card and had no hover.

That makes sense,  I do really like the one where the number of likes is displayed with a little heart (that I assume you can click to give a like). But I don't like the hover option, because I think you should be able to still click the project to go to the project-detail page instead of going straight into liking the project.

> Yes the list view would be the same as it is now, but about the update indeed that's a good suggestion forgot about that i'll look into it. but one of the strengths of the two options system is i think that the cards have more information but less cards on a page and for the list view the other way around

I agree with you that the strength of the cards is more info, so maybe don't try to fit all that into the list-view. Great that you'll look at the designs though!

**Comment by liekevdvoort** [comment]
@julia yes i also prefer the one in the card and yes you can click that to like it 

For the hover you can still click next to the button on this one that would take you to the project detail page on the black circle would like it
![image](https://user-images.githubusercontent.com/49523639/98681385-ef179780-2362-11eb-9222-098a40dc45eb.png)

**Comment by liekevdvoort** [comment]
![image](https://user-images.githubusercontent.com/49523639/98804075-fa77cb00-2415-11eb-8f9d-9484d9750af9.png)

**Comment by liekevdvoort** [comment]
![image](https://user-images.githubusercontent.com/49523639/98806371-61e34a00-2419-11eb-9f56-4980e4873a2a.png)
![image](https://user-images.githubusercontent.com/49523639/98806386-6d367580-2419-11eb-928b-aa5109e99575.png)
