### ISSUE TITLE
Email template

### ISSUE THREAD

**Issue by niraymak** [DigitalExcellence/dex-frontend#417]
**Is your feature request related to a problem? Please describe.**
We have added SendGrid to our system to send emails but we don't have designed emails yet. 

**Describe the solution you'd like**
Design a template email in HTML which can be used for different kind of email. Use HTML so we can reuse it if we will start using a different email system.

One of the features implemented that needs a email is the user graduation system. 
https://github.com/DigitalExcellence/dex-backend/issues/287
This feature will send emails to users expecting to graduate to inform them that they can convert their account to Alumni role.
If they don't convert their account, their FHICT account will be expired.

**Production URL**

**Additional context**
This is a possible framework that I found: https://mjml.io/. This could be used, but maybe other alternatives could work better for DeX.

**Comment by NealGeilen** [comment]
Designing the email templates can be done in the SendGrid dashboard. 
These templates can be exported to a plain HTML file. 
These exported templates contain all the styling for the template.

Because the styling is included in the export and no other things are dependent on SendGrid in the HTML. 
It is possible to hold on to the current email templates if we want to stop using SendGrid. 

Therefore it is best to use the template designer in the SendGrid Dashboard. Because of its ease of use and the time savings in designing. 

@MeesvanStraten

**Comment by MeesvanStraten** [comment]
Nice! That is a relief to hear. Do you want to develop a sendgrid template
for DeX? Then we could copy and tweak styling depending on the mail we are
sending.

Op zo 3 okt. 2021 20:03 schreef Neal Geilen ***@***.***>:

**Comment by NealGeilen** [comment]
In the SendGrid dashboard, there is a Main template made. 
This template can be duplicated for future use with new emails.
