### ISSUE TITLE
Mutliple call to action options

### ISSUE THREAD

**Issue by waltersajtos** [DigitalExcellence/dex-frontend#454]
Is your feature request related to a problem? Please describe.
When the project detail page's design was made, we decided it would make sense to have multiple call-to-action buttons. With the current implementation, this is not possible

Describe the solution you'd like
In the current implementation, the call-to-action option is selected with a radio button. These should be changed to checkboxes and change the `SelectedCallToActionOption` from `Number` to `Number[]`. The connection with the backend should also be changed.

This issue is blocked until https://github.com/DigitalExcellence/dex-backend/issues/416 is completed

**Comment by RubenFricke** [comment]
Store the icon in the backend as well to keep the icons scalable.

**Comment by niraymak** [comment]
Currently there is a PR open on the backend which makes it possible to assign multiple call to actions to one project. 
https://github.com/DigitalExcellence/dex-backend/pull/440

This PR breaks the current implementation of showing the call to action. This is because the frontend expects one object instead of an array. If we want to merge the PR on the backend we should at least make it possible to show the array of call to actions and send an when inserting / updating a project.
But preferably it would also be possible to assign multiple call to actions in both the project wizard and the project edit modal.

**Comment by waltersajtos** [comment]
@RubenFricke, @niraymak, or @Arilith I assume this PR does not implement storing the cta icons in the backend right? Is this still planned or has it been dropped? I still think it doesn't add that much value, because the current designs don't really allow adding or removing cta options.

**Comment by niraymak** [comment]
> @RubenFricke, @niraymak, or @Arilith I assume this PR does not implement storing the cta icons in the backend right? Is this still planned or has it been dropped? I still think it doesn't add that much value, because the current designs don't really allow adding or removing cta options.

I guess adding cta icons could have added value. For example if you want a mail icon on your "join today" button. This could be something for next semester. Maybe we can open a new issue for the above?

But for this PR it is only necessary to:
- show multiple cta at the details page
- make it possible to add multiple cta in the wizard
- make it possible to add multiple cta in the edit project page.

**Comment by waltersajtos** [comment]
Okay, I will look into it.
