### ISSUE TITLE
Remove redundant dependencies

### ISSUE THREAD

**Issue by niraymak** [DigitalExcellence/dex-frontend#457]
**Is your feature request related to a problem? Please describe.**
Look into which packagas are redundant and remove them

**Describe the solution you'd like**
All redundant packages removed.

**Production URL**

**Additional context**

**Comment by waltersajtos** [comment]
I looked for a way to check unused dependencies and ran into `npx depcheck`.
This was the output:
![afbeelding](https://user-images.githubusercontent.com/32552097/114283768-bbdd4f80-9a4b-11eb-9e28-ee8bf64e9b9c.png)

We definitely use @webcomponents/webcomponents.js for polyfilling so that's not redundant. I think the dependencies are clear. I think the missing dependencies are typescript type bugs. All the functionalities work as expected and we don't have any redundant dependencies so I'm closing this issue.
