### ISSUE TITLE
Update edit page

### ISSUE THREAD

**Issue by RubenFricke** [DigitalExcellence/dex-frontend#536]
**Is your feature request related to a problem? Please describe.**
The edit page feels out of place in the current implementation. Update the edit page for projects.

**Describe the solution you'd like**
Update the edit page. We've been talking about processing the edit page in the modal, just like the project details page. 

**Production URL**
https://www.figma.com/file/GTR0nlTW57coac7vIYXWkO/Platform-current-version?node-id=0%3A1

**Additional context**
Our first iteration that could be used:
![image](https://user-images.githubusercontent.com/55654104/123385339-b47f0a00-d595-11eb-8acb-5af949a06051.png)
![image](https://user-images.githubusercontent.com/55654104/123385380-bea10880-d595-11eb-88d8-831736e8deb5.png)

**Comment by juliaslaats** [comment]
@MeesvanStraten @DaveBouman I'm working on fixing issue #561. But I just realised that if we implement this edit-modal that won't be an issue anymore, since the filters would just stay applied in the background like with the detail-modal.

What do you guys think about that. Would it be better to start on updating & implementing the change mentioned in this issue?

**Comment by DaveBouman** [comment]
You can continue this issue if you want to. :)

**Comment by MeesvanStraten** [comment]
@juliaslaats  Hey, Yeah I checked it out and makes sense. This way we have a nice updated edit modal and the filters will still be applied! Good that you mentioned 👍
