### ISSUE TITLE
Removing/replacing Clarity Framework

### ISSUE THREAD

**Issue by RensNooren** [DigitalExcellence/dex-frontend#94]
To prevent further issues with the front-end development we need to remove or replace the Clarity Framework.

**Comment by MaxKorlaar** [comment]
+1

![image](https://user-images.githubusercontent.com/8917249/79737603-da5ab000-82fb-11ea-9a0f-9421cdde2990.png)

**Comment by Brend-Smits** [comment]
After discussion earlier today we decided to go with: 
*** NGX-Bootstrap**
Other frameworks that were considered:
* Angular Material
* NG Lightning
* Bootstrap
* Tailwind

We also considered the option to have no framework at all, however, we decided against this due to complexity it might add in the future and the difficulty to maintain.
